---
# Deploymnet Configuration
deployment: 
  name: default

# Network Configuration
networks:
  hoif1:
    netaddr: "20.0.0.1"
    dhcplower: "20.0.0.2"
    dhcpupper: "20.0.0.254"

#Hosts Configuration
hosts:
  host1:
    image: "Ubuntu Server 20.04.ova"
    username: "dev"
    password: "ved"
    networks:
      - hoif1
    internet_adapter: bridged
  host2:
    image: "Ubuntu Server 20.04.ova"
    username: "dev"
    password: "ved"
    networks:
      - hoif1
    internet_adapter: bridged
  host3:
    image: "Ubuntu Server 20.04.ova"
    username: "dev"
    password: "ved"
    networks:
      - hoif1
    internet_adapter: bridged

