---
- hosts: all # specifies inventory book group, e.g. all
  become: true # become a different user, default root (via sudo) 
  roles:
  - basic
- hosts: master 
  become: true 
  roles:
  - master 
- hosts: worker
  become: true 
  roles: 
  - worker

